#!/bin/bash

# build: build a Docker container image for Relator.

set -ex

command_script="${0/#[!\/]*/$PWD/$0}"
cd "${command_script%/*}"/../..


docker build -f docker/php5/Dockerfile -t relator:php5 "$@" . 
