#!/bin/bash

# finalize: final steps to seal a docker image build 
#     This is also re-run by init 
#         when bind-mounting a work tree inside a new container

set -ex

:
: "running" "$0" "$@"
:

[ "$container" = 'docker' ] || 
    ( ! : "We do not appear to be in a docker container. Aborting. " )

# only scan for dependency updates in development mode
chown developer -R composer.json composer.lock vendor
( ! mountpoint /srv/src ) || su developer -c "composer update"
su developer -c "composer install" 

:
: "$0 complete"
:

