#!/bin/bash

set -ex

: "running $0"

[ "$container" = 'docker' ] || 
    ( ! : "We do not appear to be in a docker container. Aborting. " )

chown developer -R vendor
su developer -c " composer update && composer install " 

:
: "$0 complete"

