#!/bin/bash

# run: executes a Relator container, mounting the source tree into the it
#     The docker image will automatically be built if it does not already exist.

set -ex

command_script="${0/#[!\/]*/$PWD/$0}"
cd "${command_script%/*}"/../..

# If there's no docker image, build one
docker image ls -q relator:php5 | grep . || docker/php5/build

docker run -it --rm -v "$PWD":/srv/src relator:php5 "$@"
