#!/bin/bash

# finalize: final steps to seal a docker image build 
#     This is also re-run by init 
#         when bind-mounting a work tree inside a new container

set -e

source "${0%/*}"/env

[ "$container" = 'docker' ] || 
    ( ! echo "We do not appear to be in a docker container. Aborting. " )

set -x

mkdir -p vendor
chown developer -R composer.json composer.lock vendor
su developer -c "composer install" 

: "finalize complete"


