#!/bin/bash

set -e

source "${0%/*}"/env

# if the image is 'docker run' without the -t option, 
#   provide a proper docker run command line and exit
[ -t 0 ] || ( ! echo docker run --rm -it "$image" "$@" )

echo + "$0" "$@"

[ "$container" = 'docker' ] || 
    ( ! echo "We do not appear to be in a docker container. Aborting. " )

# if the source tree is a mountpoint, we're probably in development mode,
#   and should re-run the build finalization script in case the source has been updated.
if mountpoint "$source_dir" ; then 
    ( set -x ; "$command_dir"/finalize )
fi

set -x 

service mysql start 

exec "$@"
